<a href="https://colab.research.google.com/github/brumbab-code/MIS433/blob/main/assignment_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Bret Brumbaugh
Welcome, Bret Brumbaugh!


In [ ]:
# complete your program here
f = float(input('Please enter the temperature in Fahrenheit: '))

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 140
140.0
140.0F is 60.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
c = float(input('Please enter the temperature in Celcius:'))

print(c)

f = c * 9/5 + 32

print(f'{c}C is {f} in Fahenheit.')


Please enter the temperature in Celcius:60
60.0
60.0C is 140.0 in Fahenheit.


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = float(input('Please enter the temperature: '))
m = input('Is this in Celsius or Fahrenheit? ')

if m == 'C':
  result = d * 9/5 + 32
  print(f'{d} Celsius is {result} in Farenheit')

else:
  result = (d - 32) * 5/9
  print(f'{d} Fahrenheit is {result} in Celsius')


Please enter the temperature: 140
Is this in Celsius or Fahrenheit? F
140.0 Fahrenheit is 60.0 in Celsius


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
print(len(sentence))


48


In [ ]:
# Convert the whole string to lower case.
print(sentence.lower())



talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[9:-9])


heap. Show me the code - Linus


In [ ]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split(' '))


['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
# Given the sentence, output a list of words in lowercase (without symbols such as '.' and '-').
print(sentence.lower().replace('.','').replace('-','').split())


['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [2]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
count = 0

for v in vowels:
 count+= sentence.count(v)
print(count)


16


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(sentence)):
  if sentence[i] in vowels:
    print(i)
    ...

1
5
10
11
17
21
25
28
30
35
37
41
44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for number in range(5):
  cubes.append(number ** 3)

print(cubes)


[0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
cubes = [number ** 3 for number in range(5)]
print(cubes)


In [3]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
position = [i for i in range(len(sentence)) if sentence[i] in vowels]
print(position)


[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]


In [8]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = int(input('How many numbers do you want? '))

a, b = 0, 1

for i in range(n):
  fibonacci.append(a)
  a, b = b, a + b

print(fibonacci)


# add your code here




How many numbers do you want? 3
[0, 1, 1]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [34]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer':0.95,'Moderna': 0.95, 'AstraZeneca':0.72, 'Johnson & Johnson':0.66}

In [35]:
v = input('Which vaccine? ')

print(f'{v} has an efficacy of {v_dict[v]}')

# print the efficacy of the vaccine



Which vaccine? Pfizer
Pfizer has an efficacy of 0.95


In [36]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914
print(v_dict['Sputnik V'])


0.914


In [37]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary

v_dict['Sinovac'] = 0.5038
print(v_dict['Sinovac'])


0.5038


In [38]:
# Print vaccines with efficacy lower than 90%.

for v in v_dict:
  if v_dict[v] < 0.90:
    print(v)



AstraZeneca
Johnson & Johnson
Sinovac


In [40]:
# delete the Sinovac vaccine from the dictionary.

del v_dict['Sinovac']
print(v_dict)


{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [49]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'
ch_dict = {}

for ch in sentence:
    if ch != ' ':
        if ch in ch_dict:
            ch_dict[ch] += 1
        else:
            ch_dict[ch] = 1

# Save the result in a dictionary
# Use a loop to iterate all characters
# add your code here

# print the dictionary
print(ch_dict)



{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [7]:
import numpy as np

In [8]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [9]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [10]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
print(M)

[[ 1.60999799 -0.76871101 -0.49908306 -1.35708547  0.37011278 -1.30426943
  -0.78161576 -0.69543647  0.02955731 -0.78132758]
 [ 0.32470416 -0.64975579  0.41728699  1.46713049 -0.43745531  0.69734956
   2.23308029 -0.1612424  -1.67825056 -0.51347901]
 [ 0.44326827  0.72717988  0.22610945 -1.0696897  -0.05299422  1.21665639
   0.36553801 -1.45818404  2.0880408  -0.17039061]
 [ 0.24294359  2.67918131 -2.24466841 -0.15502308  0.13181162 -0.69020092
  -1.78178625  1.20221862  1.14172271  0.19683606]
 [ 0.40619969 -0.81168456  1.53079602  0.02655032 -0.18598959  0.58508424
   1.39881771  0.7125938  -0.48088569 -0.09651909]
 [-0.83045913  0.22273627  0.47295913  0.93169698  1.96262257  0.74035971
   0.09585668 -0.60307038  0.17774479  0.4291333 ]
 [ 1.82500415  0.91789078  0.5326899   1.00387441  0.48400793  1.53867812
   0.51296973 -0.11804786  0.79323086 -0.08750822]
 [ 0.69922644  0.77304302 -1.29109094  1.03390596  0.70447761 -0.39138295
  -0.5512776  -0.10979096 -1.4662571   0.02218088]


In [12]:
# Count the numbers in M with an absolute value greater than 1.
count = 0
for row in M:
  for x in row:
    if abs(x) > 1:
      count += 1

print(count)





29


In [44]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = int(input('Row count: '))

# Input the number of rows (input another integer >= 3)
c = int(input('column count: '))

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10,20,(r, c))
arr

Row count: 10
column count: 10


array([[19, 19, 10, 18, 11, 13, 14, 19, 12, 18],
       [12, 12, 13, 14, 16, 14, 16, 10, 19, 11],
       [13, 18, 10, 10, 17, 12, 14, 17, 19, 18],
       [19, 10, 14, 15, 18, 17, 18, 18, 15, 16],
       [19, 17, 12, 10, 11, 11, 10, 13, 19, 19],
       [14, 15, 17, 12, 12, 15, 14, 17, 12, 12],
       [18, 17, 11, 11, 16, 11, 18, 16, 11, 17],
       [10, 14, 15, 14, 18, 13, 10, 16, 19, 13],
       [15, 16, 14, 10, 18, 12, 13, 11, 19, 12],
       [15, 15, 13, 10, 12, 17, 19, 15, 10, 12]])

In [45]:
# output the element in the first row and the third column
arr[0,2]


np.int64(10)

In [46]:
# output the element in the second row and the last column
arr[1,-1]


np.int64(11)

In [47]:
# output the second row of the array
arr[1,:]


array([12, 12, 13, 14, 16, 14, 16, 10, 19, 11])

In [48]:
# output the second last row of the array
arr[-2,:]

array([15, 16, 14, 10, 18, 12, 13, 11, 19, 12])

In [49]:
# output the second column of the array
arr[:,1]


array([19, 12, 18, 10, 17, 15, 17, 14, 16, 15])

In [50]:
# output the second last column of the array
arr[:,-2]


array([12, 19, 19, 15, 19, 12, 11, 19, 19, 10])

In [51]:
# output the upper-left 3x3 sub-array
arr[:3,:3]


array([[19, 19, 10],
       [12, 12, 13],
       [13, 18, 10]])

In [52]:
# output the bottom-left 3x3 sub-array
arr[-3:,-3:]


array([[16, 19, 13],
       [11, 19, 12],
       [15, 10, 12]])

In [53]:
# output the upper-right 3x3 sub-array

arr[:3,-3:]


array([[19, 12, 18],
       [10, 19, 11],
       [17, 19, 18]])

In [54]:
# output the bottom-right 3x3 sub-array
arr[-3:,-3:]


array([[16, 19, 13],
       [11, 19, 12],
       [15, 10, 12]])

In [55]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1,51)
# Reshape A to a 5x10 array in the following format:
A = A.reshape(5,10)
A
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [56]:
# add a row [51,...,60] to A
A = np.vstack([A, np.arange(51, 61)])
A







array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [63]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1 = A[:3]
A2 = A[3:]
print(A1)
print(A2)



[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [64]:
# Add 10 to each element of A
A + 10


array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [65]:
# Calculate the square root of each element in A
np.sqrt(A)


array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669]])

In [66]:
# Above, we should have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [68]:
# Print the mean, standard devietion of all numbers in M
print(np.mean(M))
print(np.std(M))


0.2416202213527128
0.9741215293064569


In [69]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(np.max(M))
print(np.percentile(M,75))
print(np.median(M))
print(np.percentile(M,25))
print(np.min(M))


2.99139520215732
0.730474838509968
0.22798719751810223
-0.40495296073167253
-2.2446684081902437
